[package]
name = "sensorium-dsp"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
fundsp = { workspace = true }
rubato = { workspace = true }
bumpalo = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }